# Generated by Django 2.2.3 on 2020-02-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_papers_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papers',
            name='content',
        ),
        migrations.RemoveField(
            model_name='papers',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='papers',
            name='size',
            field=models.IntegerField(default=1024, verbose_name='文件大小'),
        ),
        migrations.AlterField(
            model_name='papers',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
    ]
