# Generated by Django 2.2.3 on 2020-04-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20200422_2136'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='menu',
            field=models.ManyToManyField(blank=True, to='rbac.Menu', verbose_name='菜单列表'),
        ),
    ]
