# Generated by Django 2.2.3 on 2020-01-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200121_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.SmallIntegerField(choices=[(0, '超级管理员'), (1, '一级用户'), (2, '二级用户')], default=2, verbose_name='用户级别'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=32, verbose_name='性别'),
        ),
    ]
