# Generated by Django 2.2.3 on 2020-02-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_pod_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=64, null=True, verbose_name='用户')),
                ('role', models.SmallIntegerField(choices=[(0, '系统日志'), (1, '一级用户日志'), (2, '二级用户日志')], default=0, verbose_name='日志级别')),
                ('event_type', models.SmallIntegerField(choices=[(1, '登陆'), (2, '退出'), (3, '登陆错误'), (4, '修改密码失败'), (5, '修改密码成功'), (6, '新增用户'), (7, '删除用户用户'), (8, '更新用户信息'), (9, '创建虚拟主机'), (10, '创建失败'), (11, '删除虚拟主机'), (12, '建立ssh连接'), (13, '关闭ssh连接'), (14, '建立vnc连接'), (15, '关闭vnc连接'), (16, '导出主机数据'), (17, '申请子账户'), (18, '批准子账户'), (19, '访问首页'), (20, '访问容器信息'), (21, '访问个人页面'), (22, '访问文件上传'), (23, '上传文件'), (24, '访问文件列表'), (25, '删除文件')], default=1, verbose_name='事件类型')),
                ('detail', models.TextField(default='登陆成功', verbose_name='事件详情')),
                ('address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('useragent', models.CharField(blank=True, max_length=512, null=True, verbose_name='User_Agent')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='事件时间')),
                ('other', models.TextField(verbose_name='系统事件')),
            ],
            options={
                'verbose_name': '用户操作日志',
                'verbose_name_plural': '用户操作日志',
                'ordering': ['-create_time'],
            },
        ),
    ]
