# Generated by Django 2.2.3 on 2020-01-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200121_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(default='/media/default.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.SmallIntegerField(choices=[(0, '超级管理员'), (1, '一级用户'), (2, '二级用户')], default=1, verbose_name='用户级别'),
        ),
    ]
