# Generated by Django 2.2.3 on 2020-01-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200122_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_login_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='最后登录时间'),
        ),
    ]
