# Generated by Django 2.2.3 on 2020-01-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Systemos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(choices=[('Ubuntu', 'Ubuntu'), ('Centos', 'centos')], max_length=64, verbose_name='操作系统')),
                ('language', models.CharField(blank=True, choices=[('Python3', 'Python3'), ('Python2', 'Python2'), ('java1.8', 'java1.8')], max_length=64, null=True, verbose_name='编程语言')),
                ('database', models.CharField(blank=True, choices=[('mysql5.7', 'mysql5.7'), ('Redis', 'Redis'), ('MongoDB', 'MongoDB')], max_length=64, null=True, verbose_name='数据库')),
                ('proxy', models.CharField(blank=True, max_length=64, null=True, verbose_name='代理')),
                ('is_vnc', models.BooleanField(verbose_name='是否需要vnc')),
                ('port', models.IntegerField(blank=True, max_length=5, null=True, verbose_name='开放端口')),
                ('use_time', models.IntegerField(max_length=2, verbose_name='租用时长')),
            ],
            options={
                'verbose_name': '用户配置列',
                'verbose_name_plural': '用户配置',
            },
        ),
    ]
