# Generated by Django 2.2.3 on 2020-01-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemos',
            name='database',
            field=models.CharField(blank=True, choices=[('null', '空'), ('mysql5.7', 'mysql5.7'), ('Redis', 'Redis'), ('MongoDB', 'MongoDB')], max_length=64, null=True, verbose_name='数据库'),
        ),
        migrations.AlterField(
            model_name='systemos',
            name='language',
            field=models.CharField(blank=True, choices=[('null', '空'), ('Python3', 'Python3'), ('Python2', 'Python2'), ('java1.8', 'java1.8')], max_length=64, null=True, verbose_name='编程语言'),
        ),
        migrations.AlterField(
            model_name='systemos',
            name='os',
            field=models.CharField(choices=[('null', '空'), ('Ubuntu', 'Ubuntu'), ('Centos', 'centos')], max_length=64, verbose_name='操作系统'),
        ),
    ]
