# Generated by Django 2.2.3 on 2020-01-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectos', '0002_systemos_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemos',
            name='storage',
            field=models.IntegerField(default='5', verbose_name='硬盘容量G'),
        ),
    ]
