# Generated by Django 2.2.3 on 2020-01-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectos', '0002_auto_20200120_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemos',
            name='database',
            field=models.CharField(blank=True, choices=[(0, 'null'), (1, 'mysql5.7'), (2, 'Redis'), (3, 'MongoDB')], max_length=64, null=True, verbose_name='数据库'),
        ),
        migrations.AlterField(
            model_name='systemos',
            name='is_vnc',
            field=models.BooleanField(default=True, verbose_name='是否需要vnc'),
        ),
        migrations.AlterField(
            model_name='systemos',
            name='language',
            field=models.CharField(blank=True, choices=[(0, 'Python2'), (1, 'Python3'), (2, 'java1.8')], max_length=64, null=True, verbose_name='编程语言'),
        ),
        migrations.AlterField(
            model_name='systemos',
            name='os',
            field=models.CharField(choices=[(0, 'Ubuntu'), (1, 'Centos')], max_length=64, verbose_name='操作系统'),
        ),
    ]
