# Generated by Django 2.2.3 on 2020-02-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectos', '0002_systemos_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemos',
            name='active_status',
            field=models.SmallIntegerField(default=1, verbose_name='容器状态'),
        ),
        migrations.AlterField(
            model_name='systemos',
            name='deployment',
            field=models.CharField(choices=[(0, 'Ubuntu'), (1, 'Centos'), (2, 'Ubuntu 16.04'), (3, 'Ubuntu 14.04')], default='emp_name', max_length=64, unique=True, verbose_name='deployment_name'),
        ),
        migrations.AlterField(
            model_name='systemos',
            name='os',
            field=models.CharField(choices=[(0, 'Ubuntu'), (1, 'Centos'), (2, 'Ubuntu 16.04'), (3, 'Ubuntu 14.04')], max_length=64, verbose_name='操作系统'),
        ),
    ]
