# Generated by Django 2.2.3 on 2020-02-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectos', '0003_auto_20200208_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptDep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(default='default', max_length=63, verbose_name='命名空间')),
                ('deployment', models.CharField(default='emp_name', max_length=64, unique=True, verbose_name='deployment_name')),
                ('cpus', models.IntegerField(default=1, verbose_name='cpu个数')),
                ('ram', models.IntegerField(default=2048, verbose_name='内存容量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '异常表',
                'verbose_name_plural': '异常表',
            },
        ),
        migrations.AlterField(
            model_name='systemos',
            name='deployment',
            field=models.CharField(default='emp_name', max_length=64, unique=True, verbose_name='deployment_name'),
        ),
    ]
