# Generated by Django 2.2.3 on 2020-01-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectos', '0003_auto_20200125_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemos',
            options={'verbose_name': '用户配置', 'verbose_name_plural': '用户配置'},
        ),
        migrations.AddField(
            model_name='systemos',
            name='cpus',
            field=models.IntegerField(default=1, verbose_name='cpu个数'),
        ),
        migrations.AddField(
            model_name='systemos',
            name='create_time',
            field=models.IntegerField(default=1580114569, verbose_name='创建时间戳'),
        ),
        migrations.AddField(
            model_name='systemos',
            name='deployment',
            field=models.CharField(choices=[(0, 'Ubuntu'), (1, 'Centos')], default='emp_name', max_length=64, verbose_name='deployment_name'),
        ),
        migrations.AddField(
            model_name='systemos',
            name='ram',
            field=models.IntegerField(default=2048, verbose_name='内存容量'),
        ),
        migrations.AddField(
            model_name='systemos',
            name='version',
            field=models.CharField(default='apps/v1', max_length=8, verbose_name='容器版本'),
        ),
    ]
