# Generated by Django 2.2.3 on 2020-01-30 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selectos', '0004_systemos_namespace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_user', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
