# Generated by Django 2.2.3 on 2020-01-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectos', '0004_auto_20200127_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemos',
            name='create_time',
            field=models.IntegerField(default=1580119994, verbose_name='创建时间戳'),
        ),
        migrations.AlterField(
            model_name='systemos',
            name='deployment',
            field=models.CharField(choices=[(0, 'Ubuntu'), (1, 'Centos')], default='emp_name', max_length=64, unique=True, verbose_name='deployment_name'),
        ),
    ]
