# Generated by Django 2.2.3 on 2020-01-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectos', '0008_auto_20200127_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemos',
            name='create_time',
            field=models.IntegerField(default=1580127469, verbose_name='创建时间戳'),
        ),
    ]
